/* =========================================================
   withFullScreenCallIntent — Expo config plugin.

   notifee's `fullScreenAction` needs the launched activity to
   set `android:showWhenLocked` and `android:turnScreenOn`, or
   Android quietly downgrades the incoming-call notification to
   an ordinary heads-up banner instead of waking the screen over
   the lock screen (notifee/Android docs, "Full-screen intent").

   android/ is gitignored and regenerated by `expo prebuild`, so
   this has to be a config plugin rather than a hand edit — a
   prebuild would silently wipe a direct AndroidManifest.xml
   change.
   ========================================================= */
const { AndroidConfig, withAndroidManifest } = require('@expo/config-plugins')

module.exports = function withFullScreenCallIntent(config) {
  return withAndroidManifest(config, config => {
    const mainActivity = AndroidConfig.Manifest.getMainActivityOrThrow(config.modResults)
    mainActivity.$['android:showWhenLocked'] = 'true'
    mainActivity.$['android:turnScreenOn'] = 'true'
    return config
  })
}
