/* Splash handoff gate (src/lib/splash.ts).

   The launch has two splash screens — the OS one and BootGate's — and they
   read as one surface only because the second draws its mark at exactly the
   size and colour the first did. That size is not a constant anyone can look
   up: it is DERIVED from two numbers that live in different files and in
   different languages,

     scripts/brand-assets.py   the ink box is 0.74 of splash-icon.png's canvas
     app.json                  that canvas renders at imageWidth 120

   and the ground is a third, in src/theme/tokens.ts. Change any one of them
   and nothing fails to compile, nothing fails to run, and the app quietly
   goes back to shrinking its own logo by two and a half times in front of the
   user on every cold start. This re-derives all of it from the real files.

   Run: node scripts/check-splash.mjs — exits 1 on regression. */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const read = rel => readFileSync(join(root, rel), 'utf8')

const fail = []

/* ---- 1. what app.json asks the OS for ---- */
const appJson = JSON.parse(read('app.json'))
const plugin = (appJson.expo.plugins ?? []).find(p => Array.isArray(p) && p[0] === 'expo-splash-screen')
if (!plugin) fail.push('app.json no longer configures the expo-splash-screen plugin')
const splash = plugin?.[1] ?? {}

if (splash.image !== './assets/images/splash-icon.png') {
  fail.push(`the splash image is ${splash.image} — the derivation below reads splash-icon.png's recipe`)
}
/* `contain` is what makes "the canvas is imageWidth wide" true. Under `cover`
   the canvas is cropped to the screen and the mark's size stops being a
   function of imageWidth at all. */
if (splash.resizeMode !== 'contain') {
  fail.push(`splash resizeMode is ${splash.resizeMode} — the mark height is only derivable under 'contain'`)
}

/* ---- 2. how brand-assets.py draws that file ---- */
const gen = read('scripts/brand-assets.py')
const drawn = gen.match(/coverage\(d,\s*ink,\s*(\d+),\s*([\d.]+)\),\s*\w+,\s*A\('assets\/images\/splash-icon\.png'\)/)
if (!drawn) fail.push('scripts/brand-assets.py no longer draws assets/images/splash-icon.png in the shape this gate reads')

/* ---- 3. what src/lib/splash.ts believes ---- */
const lib = read('src/lib/splash.ts')
const claim = lib.match(/NATIVE_MARK_HEIGHT\s*=\s*(\d+)\s*\*\s*([\d.]+)\s*\*\s*\((\d+)\s*\/\s*(\d+)\)/)
if (!claim) fail.push('src/lib/splash.ts no longer derives NATIVE_MARK_HEIGHT as canvas × fraction × (imageWidth / canvas)')

if (drawn && claim) {
  const [, canvas, fraction] = drawn
  const [, c1, f, w, c2] = claim
  if (c1 !== canvas || c2 !== canvas) fail.push(`splash-icon.png is drawn on a ${canvas}px canvas, NATIVE_MARK_HEIGHT assumes ${c1}/${c2}`)
  if (f !== fraction) fail.push(`brand-assets.py draws the ink at ${fraction} of the canvas, NATIVE_MARK_HEIGHT assumes ${f}`)
  if (Number(w) !== splash.imageWidth) fail.push(`app.json renders it at imageWidth ${splash.imageWidth}, NATIVE_MARK_HEIGHT assumes ${w}`)
}

/* ---- 4. one ground, three files ---- */
const tokens = read('src/theme/tokens.ts')
const brandBlock = tokens.slice(tokens.indexOf('brand: {'), tokens.indexOf('}', tokens.indexOf('950:', tokens.indexOf('brand: {'))))
const brand900 = brandBlock.match(/900:\s*'(#[0-9A-Fa-f]{6})'/)?.[1]
if (!brand900) fail.push('could not read ramp.brand[900] out of src/theme/tokens.ts')
else {
  const eq = (a, b) => String(a).toUpperCase() === String(b).toUpperCase()
  if (!eq(splash.backgroundColor, brand900)) {
    fail.push(`app.json's splash ground is ${splash.backgroundColor}, ramp.brand[900] is ${brand900} — BootGate paints the ramp, so the handoff would change colour`)
  }
  const androidColors = read('android/app/src/main/res/values/colors.xml')
  const nativeGround = androidColors.match(/name="splashscreen_background"[^>]*>(#[0-9A-Fa-f]{6})</)?.[1]
  /* Generated by prebuild, so a mismatch means the checked-in android/ is
     stale rather than wrong — still worth saying out loud. */
  if (nativeGround && !eq(nativeGround, brand900)) {
    fail.push(`android/…/colors.xml still carries ${nativeGround} — run npx expo prebuild`)
  }
}

if (fail.length) {
  console.error('splash handoff:')
  for (const f of fail) console.error('  ✗ ' + f)
  process.exit(1)
}
const h = Number(claim[1]) * Number(claim[2]) * (Number(claim[3]) / Number(claim[4]))
console.log(`splash handoff: OK — the OS draws the mark at ${h.toFixed(1)}pt on ${brand900}, and BootGate meets it there.`)
